<<<<<<< HEAD
# fly.toml app configuration file generated for persona on 2024-06-16T10:29:29-04:00
=======
# fly.toml app configuration file generated for persona on 2024-06-16T14:54:44-04:00
>>>>>>> 35e6c918278ed3121b4634947c8b92ae2add6844
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'persona'
primary_region = 'iad'

[build]
  builder = 'heroku/builder:24'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
